version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /src
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
    allow:
      - dependency-type: all
