# SPDX-FileCopyrightText: © 2023 Kevin Lu
# SPDX-Licence-Identifier: AGPL-3.0-or-later
name: Download Forbidden & Limited Lists
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update
  schedule:
    - cron: "5 0 * * *"
jobs:
  tcg:
    name: Download TCG Forbidden & Limited Lists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn
      - run: yarn download-tcg
      - uses: ./.github/actions/commit-push
        with:
          message: "Download TCG Forbidden & Limited Lists: ${{ github.run_number }} (${{ github.run_id }})"
  ocg:
    name: Download OCG Forbidden & Limited Lists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn
      - run: curl -fsSLo /tmp/cards.json https://github.com/DawnbrandBots/yaml-yugi/raw/aggregate/cards.json
      - run: yarn download-ocg /tmp/cards.json
      - uses: ./.github/actions/commit-push
        with:
          message: "Download OCG Forbidden & Limited Lists: ${{ github.run_number }} (${{ github.run_id }})"
  rush:
    name: Download Rush Duel Forbidden & Limited Lists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn
      - run: curl -fsSLo /tmp/rush.json https://github.com/DawnbrandBots/yaml-yugi/raw/aggregate/rush.json
      - run: yarn download-rush /tmp/rush.json
      - uses: ./.github/actions/commit-push
        with:
          message: "Download Rush Duel Forbidden & Limited Lists: ${{ github.run_number }} (${{ github.run_id }})"
  master-duel:
    name: Transform Master Duel Forbidden & Limited Lists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: yaml-yugi
      - uses: actions/checkout@v3
        with:
          repository: DawnbrandBots/yaml-yugipedia
          path: yaml-yugipedia
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: yaml-yugi/src/requirements.txt
      - run: pip install -r yaml-yugi/src/requirements.txt
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yaml-yugi/yarn.lock
      - working-directory: yaml-yugi
        run: yarn
      - run: curl -fsSLo /tmp/cards.json https://github.com/DawnbrandBots/yaml-yugi/raw/aggregate/cards.json
      - working-directory: yaml-yugi/data/limit-regulation/master-duel
        run: python ../../../src/limit-regulation/masterduel-extract-transform.py ../../../../yaml-yugipedia/wikitext/master-duel-limit-regulation
      - working-directory: yaml-yugi
        run: yarn transform-md /tmp/cards.json
      - uses: ./.github/actions/commit-push
        with:
          message: "Transform Master Duel Forbidden & Limited Lists: ${{ github.run_number }} (${{ github.run_id }})"
