name: Merge all data sources

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update

jobs:
  merge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yaml-yugi
    steps:
      - uses: actions/checkout@v3
        with:
          path: yaml-yugi
      - uses: actions/checkout@v3
        with:
          repository: DawnbrandBots/yaml-yugipedia
          path: yaml-yugipedia
          token: ${{ secrets.TEST_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: DawnbrandBots/yaml-yugi-zh
          path: yaml-yugi-zh
          token: ${{ secrets.TEST_TOKEN }}
      - uses: actions/checkout@v3
        with:
          path: aggregate
          ref: aggregate
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: pip
      - run: pip install -r src/requirements.txt
      - run: cd data && python3 ../src/main.py ../../yaml-yugipedia/wikitext/cards ../../yaml-yugi-zh/zh-CN
      - name: Commit
        id: commit
        run: |
          git config user.name GitHub Actions
          git config user.email noreply@github.com
          git add .
          git commit -m "Transform: ${{ github.run_number }} (${{ github.run_id }})"
          git pull --rebase
          git push
      - name: Merge
        run: |
          sed -s '1i---' data/*.yaml > ../aggregate/cards.yaml
      - working-directory: aggregate
        name: Commit aggregate
        run: |
          git add .
          git commit -m "Merge: ${{ github.run_number }} (${{ github.run_id }})" -m "$(git -C ../yaml-yugi rev-parse @)"
          git pull --rebase
          git push
