# SPDX-FileCopyrightText: © 2022–2023 Kevin Lu
# SPDX-Licence-Identifier: AGPL-3.0-or-later
name: Merge cached data
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update

jobs:
  merge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yaml-yugi
    steps:
      - uses: actions/checkout@v4
        with:
          path: yaml-yugi
      - uses: actions/checkout@v4
        with:
          path: aggregate
          ref: aggregate
      - name: Merge JSON (OCG+TCG)
        run: |
          cd data/cards
          node ../../src/merge.js ../../../aggregate/cards.json
      - name: Merge JSON (Rush)
        run: |
          cd data/rush
          node ../../src/merge.js ../../../aggregate/rush.json
      - name: Merge YAML
        run: |
          sed -s '1i---' data/cards/*.yaml > ../aggregate/cards.yaml
          sed -s '1i---' data/rush/*.yaml > ../aggregate/rush.yaml
      - working-directory: aggregate
        name: Commit aggregate
        run: |
          git config user.name GitHub Actions
          git config user.email noreply@github.com
          git add .
          git commit -m "Merge: ${{ github.run_number }} (${{ github.run_id }})" -m "$(git -C ../yaml-yugi rev-parse @)"
          git pull --rebase origin aggregate
          git push
