# SPDX-FileCopyrightText: © 2022–2023 Kevin Lu
# SPDX-Licence-Identifier: AGPL-3.0-or-later
name: Merge all data sources

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: yaml-yugi
      - uses: actions/checkout@v3
        with:
          repository: DawnbrandBots/yaml-yugipedia
          path: yaml-yugipedia
      - uses: actions/checkout@v3
        with:
          path: yaml-yugi-ko
          repository: DawnbrandBots/yaml-yugi-ko
          sparse-checkout: |
            /*.csv
            /overrides.tsv
          sparse-checkout-cone-mode: false
      - uses: actions/checkout@v3
        with:
          repository: DawnbrandBots/yaml-yugi-zh
          path: yaml-yugi-zh
      - uses: actions/checkout@v3
        with:
          path: aggregate
          ref: aggregate
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: yaml-yugi/src/requirements.txt
      - name: Download yaml-yugi-ko exports
        run: |
          curl -fsSLO https://dawnbrandbots.github.io/yaml-yugi-ko/ocg.csv
      - run: pip install -r yaml-yugi/src/requirements.txt
      - name: Transform (series)
        working-directory: yaml-yugi/data/series
        run: python3 ../../src/main_archetypes.py ../../../yaml-yugipedia/wikitext/archetypes
      - name: Transform (OCG+TCG)
        working-directory: yaml-yugi/data/cards
        run: |
          git rm --ignore-unmatch kdb*.json kdb*.yaml yugipedia*.json yugipedia*.yaml
          python3 ../../src/main_ocgtcg.py \
            ../../../yaml-yugipedia/wikitext/cards \
            --zh-CN ../../../yaml-yugi-zh/zh-CN \
            --assignments ../../src/assignments/assignments.yaml \
            --tcg ../../data/limit-regulation/tcg/current.vector.json \
            --ocg ../../data/limit-regulation/ocg/current.vector.json \
            --ko ../../../yaml-yugi-ko/overrides.tsv \
            --ko-official ../../../ocg.csv \
            --ko-override ../../../yaml-yugi-ko/ocg-override.csv \
            --ko-prerelease ../../../yaml-yugi-ko/ocg-prerelease.csv \
            --aggregate ../../../aggregate/cards.json
      - name: Transform (Rush Duel)
        working-directory: yaml-yugi/data/rush
        run: |
          git rm --ignore-unmatch yugipedia*.json yugipedia*.yaml
          python3 ../../src/main_rush.py \
            ../../../yaml-yugipedia/wikitext/rush \
            --aggregate ../../../aggregate/rush.json
      - name: Transform (TCG Speed Duel Skills)
        working-directory: yaml-yugi/data/tcg-speed-skill
        run: |
          git rm --ignore-unmatch *.json *.yaml
          python3 ../../src/main_speed.py \
            ../../../yaml-yugipedia/wikitext/speed \
            --aggregate ../../../aggregate/skill.json
      - id: commit
        uses: ./yaml-yugi/.github/actions/commit-push
        with:
          message: "Transform: ${{ github.run_number }} (${{ github.run_id }})"
          working-directory: yaml-yugi
      - if: steps.commit.outputs.status > 0
        working-directory: yaml-yugi
        run: gh workflow run validate-data.yaml
        env:
          GH_TOKEN: ${{ github.token }}
      - if: steps.commit.outputs.status > 0
        working-directory: yaml-yugi
        name: Merge
        run: |
          sed -s '1i---' data/cards/*.yaml > ../aggregate/cards.yaml
          sed -s '1i---' data/rush/*.yaml > ../aggregate/rush.yaml
      - if: steps.commit.outputs.status > 0
        working-directory: aggregate
        name: Commit aggregate
        run: |
          git config user.name GitHub Actions
          git config user.email noreply@github.com
          git add .
          git commit -m "Merge: ${{ github.run_number }} (${{ github.run_id }})" -m "$(git -C ../yaml-yugi rev-parse @)"
          git pull --rebase origin aggregate
          git push
      - if: steps.commit.outputs.status > 0
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yaml-yugi/yarn.lock
      - if: steps.commit.outputs.status > 0
        working-directory: yaml-yugi
        run: yarn
      - if: steps.commit.outputs.status > 0
        working-directory: yaml-yugi
        name: Load (push)
        env:
          OPENSEARCH_URL: ${{ secrets.OS_URL }}
        run: |
          yarn ts-node src/load.ts ../aggregate/cards.yaml yu-gi-oh_ocg-tcg_20230501
          yarn ts-node src/load.ts ../aggregate/rush.yaml yu-gi-oh_rush_20230501
