# SPDX-FileCopyrightText: © 2022 Kevin Lu
# SPDX-Licence-Identifier: AGPL-3.0-or-later
name: Merge all data sources

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update

jobs:
  merge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yaml-yugi
    steps:
      - uses: actions/checkout@v3
        with:
          path: yaml-yugi
      - uses: actions/checkout@v3
        with:
          repository: DawnbrandBots/yaml-yugipedia
          path: yaml-yugipedia
      - uses: actions/checkout@v3
        with:
          repository: DawnbrandBots/yaml-yugi-zh
          path: yaml-yugi-zh
      - uses: actions/checkout@v3
        with:
          path: aggregate
          ref: aggregate
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: yaml-yugi/src/requirements.txt
      - run: cd .. && curl -fsSLO https://github.com/DawnbrandBots/yaml-yugi-ko/raw/master/overrides.tsv
      - run: pip install -r src/requirements.txt
      - name: Transform (OCG+TCG)
        working-directory: yaml-yugi/data/cards
        run: |
          git rm --ignore-unmatch kdb*.yaml yugipedia*.yaml
          python3 ../../src/main_ocgtcg.py \
            ../../../yaml-yugipedia/wikitext/cards \
            --zh-CN ../../../yaml-yugi-zh/zh-CN \
            --assignments ../../src/assignments/assignments.yaml \
            --tcg ../../data/limit-regulation/tcg/2022-10-03.vector.json \
            --ocg ../../data/limit-regulation/ocg/2022-10-01.name.json \
            --ko ../../../overrides.tsv \
            --aggregate ../../../aggregate/cards.json
      - name: Transform (Rush Duel)
        working-directory: yaml-yugi/data/rush
        run: |
          git rm --ignore-unmatch yugipedia*.yaml
          python3 ../../src/main_rush.py \
            ../../../yaml-yugipedia/wikitext/rush \
            --aggregate ../../../aggregate/rush.json
      - name: Commit
        id: commit
        run: |
          git config user.name GitHub Actions
          git config user.email noreply@github.com
          git add .
          git commit -m "Transform: ${{ github.run_number }} (${{ github.run_id }})"
          git pull --rebase
          git push
      - name: Merge
        run: |
          sed -s '1i---' data/cards/*.yaml > ../aggregate/cards.yaml
          sed -s '1i---' data/rush/*.yaml > ../aggregate/rush.yaml
      - working-directory: aggregate
        name: Commit aggregate
        run: |
          git config user.name GitHub Actions
          git config user.email noreply@github.com
          git add .
          git commit -m "Merge: ${{ github.run_number }} (${{ github.run_id }})" -m "$(git -C ../yaml-yugi rev-parse @)"
          git pull --rebase
          git push
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yaml-yugi/yarn.lock
      - run: yarn
      - name: Load (push)
        env:
          OPENSEARCH_URL: ${{ secrets.OS_URL }}
        run: |
          yarn ts-node src/load.ts ../aggregate/cards.yaml yu-gi-oh_ocg-tcg
          yarn ts-node src/load.ts ../aggregate/rush.yaml yu-gi-oh_rush
