# SPDX-FileCopyrightText: © 2022 Kevin Lu
# SPDX-Licence-Identifier: AGPL-3.0-or-later
name: Validate assignments.yaml

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/validate-assignments.yaml
      - src/assignments/**
  pull_request:
    paths:
      - .github/workflows/validate-assignments.yaml
      - src/assignments/**

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/assignments
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
          cache-dependency-path: src/assignments/requirements.txt
      - run: pip install -r requirements.txt
      - run: python validate.py
