# SPDX-FileCopyrightText: © 2022–2023 Kevin Lu
# SPDX-Licence-Identifier: AGPL-3.0-or-later
name: Validate assignments.yaml

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/validate-assignments.yaml
      - src/assignments/**
      - src/requirements*
  pull_request:
    paths:
      - .github/workflows/validate-assignments.yaml
      - src/assignments/**
      - src/requirements*

jobs:
  validate:
    name: Validate assignments.yaml
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/assignments
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: src/requirements.txt
      - run: pip install -r ../requirements.txt
      - run: python validate.py
