# SPDX-FileCopyrightText: © 2023 Kevin Lu
# SPDX-Licence-Identifier: AGPL-3.0-or-later
name: Validate data

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/validate-data.yaml
      - data/**
  pull_request:
    paths:
      - .github/workflows/validate-data.yaml
      - data/**
  workflow_dispatch:

jobs:
  validate:
    name: Validate data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn
      - name: Does not contain wikitext templates
        run: |
          ! grep {{ -R data --include='*.yaml'
      - name: Cards are not missing placeholder fake passwords
        if: success() || failure()
        run: yarn check-for-missing-fake-password data/cards
